output_path: "/scratch/indikar_root/indikar1/shared_data/population_fib_sync/"
inputs: "config/fastq_paths.txt"
ref_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/RefGenome/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz" 
transcript_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/RefGenome/Homo_sapiens.GRCh38.cdna.all.fa.gz" 
gtf_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/RefGenome/Homo_sapiens.GRCh38.107.gtf"
minimap2_args: "-ax splice -uf --secondary=no --MD" 
umi_distance: 1
threads: 36
